### ISSUE TITLE
`Authorization` header / more control over requests

### ISSUE THREAD

**Issue by unindented** [running-coder/jquery-typeahead#105]
My problem is that the endpoint that provides my results is OAuth protected, so I need to add an `Authorization: Bearer <token>` header to requests.

Ideally I'd have full control of how the request is made, as the logic may be more complex (e.g. maybe I need to request a token before making the request). Maybe it would be a good idea to allow developers to provide their own requesting function that would be used here? https://github.com/running-coder/jquery-typeahead/blob/cb0ce5c3fab10fccb57abcff4ce5db31dfefd535/src/jquery.typeahead.js#L701

That way they could customize headers and do all other crazy stuff. As long as they return a promise, everything would work the same. 

What do you think?

**Comment by unindented** [comment]
Alternatively I could use [`$.ajaxSetup`](https://api.jquery.com/jquery.ajaxsetup/) to set headers. Maybe that's the simplest way.

**Comment by unindented** [comment]
Ah, `jquery-typeahead` is overwriting my `beforeSend` here: https://github.com/running-coder/jquery-typeahead/blob/1c2d2952a542f0021eaea34ec6f686d588cf0361/src/jquery.typeahead.js#L602-L604

@running-coder what's your suggestion?

**Comment by running-coder** [comment]
Hey Daniel, I've looked into `headers` object of the jquery ajax request and it does not seem to work properly or the way I was expecting it to work. The recommend indeed to add headers to the XHR request on the beforeSend option. I'm already using this option to abort old xhr request in case of new keys being typed before the receive. I see that you've solved the issue by merging this default behaviour with the user defined option. I'll review the PR but I might have a different approach as of how the merge should occur. Also I'll add a note in the .readme but future pull requests should be done on the develop branch because the master should be the latest released version.

Thanks for the contrib!

**Comment by unindented** [comment]
Sure. Sorry about PRing on top of `master`, I didn't notice the `develop` one.

**Comment by unindented** [comment]
Do you think you are going to be working on this problem soonish? My deadline is on December, but I'd love to end up using this library...

**Comment by running-coder** [comment]
This issue should only take a couple of mins to fix & test. As I categorize it as a bug it has priority over improvements or new features. Regarding when it should happen within the next week

**Comment by unindented** [comment]
Great to hear. Thanks!

**Comment by running-coder** [comment]
Perhaps you could assist me... I'm trying to test sending headers via 

``` javascript
beforeSend: function (jqXHR, options) {
    jqXHR.setRequestHeader('Authorization', 'Bearer xxxxxxxxxxxx');
}
```

and I'm getting these weird results...

I'm expecting:

![expected](https://cloud.githubusercontent.com/assets/7377382/11154136/94542b38-8a0b-11e5-9f39-f6734710a16f.png)

But getting this instead using json request

![json](https://cloud.githubusercontent.com/assets/7377382/11154143/99f8c71a-8a0b-11e5-8a1b-b21611c3d51d.png)

And using jsonp there is no `Authorization`

![jsonp](https://cloud.githubusercontent.com/assets/7377382/11154144/9c8d6bca-8a0b-11e5-8ad4-1559855e9d90.png)

**Comment by running-coder** [comment]
Got it... works on local server, and perhaps need enabled request headers on distant server

**Comment by unindented** [comment]
:+1:

**Comment by running-coder** [comment]
So I've opted for changing the object key writable to false [@line634](https://github.com/running-coder/jquery-typeahead/blob/develop/src/jquery.typeahead.js#L634) and then calling the "user-defined" beforeSend [@line617](https://github.com/running-coder/jquery-typeahead/blob/develop/src/jquery.typeahead.js#L617) instead of adding function params.

**Comment by unindented** [comment]
:+1:
