### ISSUE TITLE
add scope to onClickBefore

### ISSUE THREAD

**Issue by ethaniel** [running-coder/jquery-typeahead#118]
Hello :) Would be really awesome, if I could access scope from within onClickBefore function. I would like to call  scope.hideLayout();

The reason that I am asking for this is that I am cloning the way Facebook search works and I need typeahead to close the dropdown when I click on a result.

<b>Easy fix</b>
Replace:
scope.helper.executeCallback(scope.options.callback.onClickBefore, [scope.node, this, item, e]);
with this:
scope.helper.executeCallback(scope.options.callback.onClickBefore, [scope.node, this, item, e, scope]);

**Comment by running-coder** [comment]
I was thinking of giving the whole Typeahead scope in every callback instead of passing parameters. The same way as I did with groupOrder option so every Typeahead properties and functions would be accessible via `this` object... 

scope.helper.executeCallback(scope.options.callback.onClickBefore.apply(scope, [scope.node, this, item, e]);

the regular parameters would be present but also `this` would be available for more advanced stuff... still need to be tested tho

**Comment by ethaniel** [comment]
beautiful.
