### ISSUE TITLE
Words width space fail

### ISSUE THREAD

**Issue by chrispcb** [running-coder/jquery-typeahead#167]
Exemple in User V1 demo. it's ok If you search in order "Thiago Talma", but no result if the order is "talma tiago". (same fail in game v3 demo with "Xin Zhao")
I have the same problem if I have 2 separates fields: last_name, first_name.

Is possible to display only a results from Backend ?
If the text typed is "Thiago Talma" or "talma tiago", the result still show "Thiago Talma" because this item is in json from backend Or plugin must separate words with a space and manage them in any order to match the input.

**Comment by running-coder** [comment]
Hey chris,

the issue comes from the fack that they are 2 seperate fields and the order missmatch as you noticed. A couple of revision ago the parameter `correlativeTemplate` was introduced to "fix" how the search behaves. That option will split the template on spaces and not on `{{item.keys}}` to allow a much more flexible search.

If your search algorithm is occurring in the backend and you simply want to display the result, you may use the `filter:false` option. You can as well set that option per source group, ex:

``` javascript

$.typeahead({
    input: '#q',
    ...
    // Disable Typeahead filtering globally 
    filter: false,  
    source: {
        myGroup: {
            // Disable Filtering only for this group
            filter: false,
            url: ...
        }
    }
})


```

**Comment by chrispcb** [comment]
Hello,

YES, ok !  filter: false. Thank you.
I seemed to have yet to try.

Do you have a exemple with a correlativeTemplate  ?

great plugin, full but not easy to master all :) ( my english is bad)

**Comment by running-coder** [comment]
[hockey_v1](http://www.runningcoder.org/jquerytypeahead/demo/#form-hockey_v1) is using `correlativeTemplate`. Try typing something like "mon ca east conf" you should see the search being a lot more permissive.
