### ISSUE TITLE
Provide a default `loading` state and animation

### ISSUE THREAD

**Issue by running-coder** [running-coder/jquery-typeahead#175]
Lets make it "out of the box" for even easier development!

**Comment by running-coder** [comment]
`loading` class will be added to `typeahead__container` when asynchronous operations are performed

**Comment by kavin-90** [comment]
thanks. any docs on how to change it or disable it?

Currently i'm using old solution for it in 2.5.0 where is** loading css** so i can change its location and use own loading gif for it?

2nd Please add Upgrade Docs for HTML because classes were changed..
____________________________________________________________________________

Jquery Ui Autocomplete Feature 

I've used Jquery-ui Autocomplete search which cache results and on focus it show it and  if user click of outside of search field it hides.

2nd What l like is result . If you mouse over it will show you URL in status bar. I don't know How to make it with This Plugin.

**Comment by running-coder** [comment]
hey kavin, the doc was updated the day of the release, perhaps you need to clear the browser cache? (my bad if its not clearing by itself)

![2016-04-07_1214](https://cloud.githubusercontent.com/assets/7377382/14358292/550c7044-fcba-11e5-9ea7-15ca347c370a.png)

To use your own loading anim, simply override the css class in your project. 

Do you have a screenshot of ``What l like is result . If you mouse over it will show you URL in status bar. I don't know How to make it with This Plugin.`` ?

Thanks

**Comment by kavin-90** [comment]
Screenshots

![jquery-ui-autocomplete](https://cloud.githubusercontent.com/assets/15142270/14358528/fbe4c34e-fd0a-11e5-841c-edfcf422b280.png)

![jquery-ui-autocomplete](https://cloud.githubusercontent.com/assets/15142270/14358690/b81c5644-fd0b-11e5-9b10-c1821f4c2fd2.png)

**Comment by running-coder** [comment]
oh, to have the `url` on mouse hover for the items you need to define the `href` option. You can have a look at [font_v1](http://www.runningcoder.org/jquerytypeahead/demo/#form-font_v1) where each group have their own `href` option

**Comment by running-coder** [comment]
`|slugify` modifier is to use Typeahead internal function to transform a string to a valid url replacing special characters and spaces by "-" [slugify function](https://github.com/running-coder/jquery-typeahead/blob/master/src/jquery.typeahead.js#L2345)

**Comment by kavin-90** [comment]
Thanks
