### ISSUE TITLE
Results remain open when clicking inside a second typeahead field

### ISSUE THREAD

**Issue by nop33** [running-coder/jquery-typeahead#192]
Hello!

I found out that when using 2 typeahead fields, there's a problem occurring when switching from one to the other using the mouse. I prepared 2 jsfiddle snippets to reproduce the issue.

http://jsfiddle.net/eyetea/pzqffwgf/3/
First, click on the Venue field (the results will open normally) and without selecting anything, click on the Room field. The results of the Venue field will remain open and clicking outside will never close them (except if you press `ESC` while the focus is on the field).

I tried to solve this problem by simply calling `hideLayout` when switching between these two fields. But then a similar problem occurs, which is that the second field results will remain open this time. Here's another jsfiddle where you can reproduce it: http://jsfiddle.net/eyetea/dw932nv7/1/

Thanks a lot and let me know if I can be of any help.
Ilias

**Comment by nop33** [comment]
Reducing and simplifying the code of the jsfiddles:
* http://jsfiddle.net/eyetea/pzqffwgf/4/
* http://jsfiddle.net/eyetea/dw932nv7/3/

**Comment by running-coder** [comment]
Hey Ilias, I haven't tested much using multiple instances of Typeahead on the same page. The problem was that I was using `.typeahead` alias for binding/unbinding events. This should now be fixed by using the `node.selector` + `.typeahead` to give unique names for events.

Let me know if everything works fine (y)
