### ISSUE TITLE
Result not showing if there is returned one object

### ISSUE THREAD

**Issue by athashmi** [running-coder/jquery-typeahead#250]
I have fetched data through ajax, when it returns more than one results, its fine, but if it returns only one object, then its not showing result.

My code for initialization is 

 ticket:{
                  display: "ticket_title",
                    href: "{{URL::route('admin.ticket.index')}}/show/@{{id}}",
                    ajax: function (query) {
                    //console.log(query);
                        return {
                            type: "GET",
                            url: "{{URL::route('admin.crm.ajax.search.tickets')}}",
                            path: "data.tickets",
                           {{--  dataType: 'json', --}}
                            data: {
                                ticket: "@{{query}}"
                            }
                        }
                    }

                }

![selection_001](https://cloud.githubusercontent.com/assets/4329911/19731673/a6e72930-9bb7-11e6-8581-638f8e8c37db.png)

**Comment by running-coder** [comment]
hi @athashmi, it seems that you are already filtering results in BE, "hh" is not supposed to match ticket_title but your BE returns something. You can disable Typeahead filtering at the config root (for all groups) or at the group level (disable filtering for that group only).

You can further more pass a `function` instead of a `boolean` and apply custom filtering to your items

http://www.runningcoder.org/jquerytypeahead/documentation/#options-filter

```javascript
ticket: {
    display: "ticket_title",
    href: "{{URL::route('admin.ticket.index')}}/show/@{{id}}",
    filter: false, // Disable Typeahead filtering for "ticket" group
    ajax: function (query) {
        return {
            type: "GET",
            url: "{{URL::route('admin.crm.ajax.search.tickets')}}",
            path: "data.tickets",
            data: {
                ticket: "@{{query}}"
            }
        }
    }
}
```

**Comment by athashmi** [comment]
got it, thanks

**Comment by running-coder** [comment]
np, let me know if anything
