### ISSUE TITLE
Can I use search functionality automatically and get results on page?

### ISSUE THREAD

**Issue by peterkocian** [running-coder/jquery-typeahead#32]
Is there any possibility to search from data source automatically e.g. based on some value from URL? I want to show results on page automatically when the page is loaded. I want to use just the search function. Thanks for answer.

**Comment by running-coder** [comment]
Hey peterkocian,

not sure if your issue is related to https://github.com/running-coder/jquery-typeahead/pull/33

If you want to display search results on page load you can use the option "searchOnFocus: true" with "minLength: 0" and add "autofocus" attribute to your search input.

These options are available with Typeahead v2.0.0-rc.1 
https://github.com/running-coder/jquery-typeahead/tree/2.0.0-rc.1
