### ISSUE TITLE
Where do I style the typeahead__filter-button?

### ISSUE THREAD

**Issue by dave7777** [running-coder/jquery-typeahead#338]
Tom - cannot find it in the CSS file - can you please help - where I can style the border of the typeahead__filter-button?

**Comment by running-coder** [comment]
hey @dave7777 thats more a programmation question than a Typeahead related. There are a lot of ways you can change the styles for that class depending on what your project allows you. To do it quick and simple I suggest you add a stylesheet after the Typeahead's one that overrides certain properties. Do not edit the typeahead's stylesheet because if you upgrade to a later version you will loose your changes.

**Comment by dave7777** [comment]
Thank you Tom - I added this style to override border colour:

.typeahead__filter button {
  min-width: 100%;
  white-space: nowrap;
  border-color:#FF0000
  
}

and it did not work(

**Comment by dave7777** [comment]
I found the styles:)
