### ISSUE TITLE
Multiple sources, single ajax call

### ISSUE THREAD

**Issue by ldrrp** [running-coder/jquery-typeahead#34]
To reduce latency ive compacted my search into one single call. But is therr a way to make them share the same ajax call for a group. I think you should match the url and any parameters passed in, and if its exactly the same, then do run the query again. just share the data.

Also, why does it make another call for ajax calls when cache is enabled.

```
source: {
           city: {
                url: [
                    {
                        type: "POST",
                        url: "/includes/send/index/search.php",
                        data: { q: "{{query}}" }
                    },
                    "data.city"
                ],
                display: "text",
                template: '<span>{{text}}</span>'
            },
            postal: {
                url: [
                    {
                        type: "POST",
                        url: "/includes/send/index/search.php",
                        data: { q: "{{query}}" }
                    },
                    "data.postal"
                ],
                display: "text",
                template: '<span>{{text}}</span>'
            },
            address: {
                url: [
                    {
                        type: "POST",
                        url: "/includes/send/index/search.php",
                        data: { q: "{{query}}" }
                    },
                    "data.address"
                ],
                display: "text",
                template: '<span>{{text}}</span>'
            }
		},
```

**Comment by running-coder** [comment]
Hey ldrrp,

good observation! I thought i was already doing it (identical request shouldn't be repeated). I'll fix that. Regarding the cache option it cannot be enabled for dynamic request, it wouldn't make sense to cache part of the data. Since every keystroke makes a new request with different data. The cache & compression options are only meant to be used when a complete set of data is requested (I'll make sure to mention this in the documentation).

**Comment by ldrrp** [comment]
Just tested this commit, seems to work. Thanks
