### ISSUE TITLE
Domain is expired

### ISSUE THREAD

**Issue by Grawl** [running-coder/jquery-typeahead#341]
I just started my work day from your website with examples and configuration and just realized your domain is expired and I cannot see live examples anymore 😢

**Comment by tsamaya** [comment]
Examples are in the repository, forked and created a gh-pages branch on my account to have them available online  (use http version because example uses http to load jquery on some samples):

http://tsamaya.github.io/jquery-typeahead/example/demo-country_v2.html
http://tsamaya.github.io/jquery-typeahead/example/demo-beer_v1.html
http://tsamaya.github.io/jquery-typeahead/example/demo-bootstrap3.html

etc...

**Comment by jkpatil211** [comment]
@tsamaya What about documentation? I need it for further enhancement in my project

**Comment by running-coder** [comment]
Documentation website should be back online, thanks for letting my know!
