### ISSUE TITLE
Natural Language Search

### ISSUE THREAD

**Issue by dave7777** [running-coder/jquery-typeahead#358]
Hello!
I know you have correlative search function but what if your search could be made to work this way?
Someone types a sentence like - **Show me the cheap hotels in London**
And the typehead shows the result which have any of these words in them - starting with the ones which have the most matches like

Cheap London Hotels

I guess the script will need to search for all words and get results with the most matches - is it possible?

Thank you for your fabulous script!
Dave

**Comment by dave7777** [comment]
No way this can be done Tom ?

**Comment by running-coder** [comment]
Hey @dave7777, currently this can't be done because Typeahead starts searching and ends as soon as it has the number of `maxLength` results so the whole stack is not parsed (faster search results). Doing this seems like a good idea to obtain better results but would require a small compromise on time to get the results (If you have 200-300 items it's fine, but 5000-10000+ items to go through might have bigger impacts in performances).

Currently is it possible to know it was a `correlativeTemplate` match knowing that the `matchKey` is `compiled`
<img width="557" alt="screen shot 2017-07-02 at 10 20 16 am" src="https://user-images.githubusercontent.com/7377382/27770635-256e508c-5f10-11e7-8547-e77cb2bc576d.png">

It would be a matter of adding an option to `fullSearch true|default false` where when enabled it perform a full data search regardless of matches. Add a new key on each items, `matchedCount` that stores a count of matched elements and add a new option `orderKey` to order by an item key.

```javascript
order: 'desc', // The most number of results first
orderKey: 'matchedCount',
fullSearch: true,
```
These changes sounds generic and could be combines to achieve different results.

**Comment by dave7777** [comment]
Thank you very much Tom....We have a few hundred lines to search through so it is OK to add this feature. We have added this code and it does not work - ignores the natural searches like SHOW ME XXXX

```
<script>

  var myData = [    ];

   $.typeahead({
  input: ".js-typeahead-input",
  minLength: 1,
  maxItemPerGroup: 20,
  maxItem: 20,
  order: 'desc', // The most number of results first
  orderKey: 'matchedCount',
  fullSearch: true,
  correlativeTemplate: true,
  emptyTemplate: 'No result for "{{query}}"',
  source: {
    myGroup: {
	ajax: {
            url: 'search/src/data2.json'
        }, 
      display: ['name', 'descr'] ,
      href: "{{link}}",
       template: '<span class="typeahead__column">{{name}}</span><span class="typeahead__column">{{descr}}</span>'
    }
  },
  group: {
                key: "category",
                template: function (item) {

                    var category = item.category;
                  

                    return category;
                }
            },
  
    dropdownFilter: [{
                key: 'category',
                template: '{{category}}',
        
            }],
            
  callback: {
    onSubmit: function (node, form, item, event) {
      var href;

      if (this.result.length === 1) {
        href = this.result[0].link;
      } else {
        console.log(this.source)

        for (var i=0, ii=this.source.myGroup.length; i<ii; ++i){
          if (this.query.toLowerCase() === this.source.myGroup[i].name.toLowerCase()) {
            href = this.source.myGroup[i].link
            break;
          }
        }
      }

      if (href) {
        event.preventDefault();
        window.location.href = href;
      }
    }
  }
});
</script>
```

**Comment by dave7777** [comment]
This would make your script into a one-of-a-kind piece of content! best in this kind! please take some time to introduce this functional...

**Comment by running-coder** [comment]
I've started looking at this last week, there are a few number of issues I'm facing when implementing it. Still need to put my head into it to find the best solution that would be viable using other options as well :)

**Comment by dave7777** [comment]
That is a wonderful news! looking eagerly to see what you create Tom!
