### ISSUE TITLE
jQuery dropdown menu falls behind search box with multiple fields

### ISSUE THREAD

**Issue by MsWebGirl** [running-coder/jquery-typeahead#386]
I am in the process of tweaking with CSS, but when one has multiple jQuery typeahead search boxes, the dropdown drops behind the search box. See screenshot. When I have successfully implemented my solution, I will submit a pull request. [screencapture](https://user-images.githubusercontent.com/7428095/31823163-259ce9c8-b579-11e7-8c87-82450d41f564.PNG)

**Comment by running-coder** [comment]
Hey @MsWebGirl I'm unable to repro the issue, could it be because some other library overrides some of the Typeahead `z-index` styles? This dropdown should be set to a `z-index: 1001`

![image](https://user-images.githubusercontent.com/7377382/31838791-5be16c6a-b5ac-11e7-92f5-0ac45b6c552e.png)

![image](https://user-images.githubusercontent.com/7377382/31838852-8534b7e8-b5ac-11e7-9360-d8b2fc7db55a.png)

**Comment by MsWebGirl** [comment]
Hmmmmmm That's what I have but the issue remains

**Comment by running-coder** [comment]
Could it be possible that your Typeaheads have a parent container that have a “position: “ set? In that case the z-index would be relative to that parent and cause the issue

**Comment by MsWebGirl** [comment]
I was able to put a Z-index on the form itself and that seems to have resolved it. Thanks anyway for your advice!
