### ISSUE TITLE
Custom sort

### ISSUE THREAD

**Issue by Chryogenic** [running-coder/jquery-typeahead#391]
Hello,

Is there anyway to implement a custom sort of the listed results? I would like to sort my results based off an integer rather than my {{title}} display key.

Perhaps using using onLayoutBuiltBefore and sorting the resultHtmlList?

Thanks,

**Comment by Chryogenic** [comment]
I have this - but it overrides a lot of the settings which is probably not ideal:

```javascript
onLayoutBuiltBefore: function (node, query, result, resultHtmlList)
 {
                if (result != null)
                {
                    result.sort(function (a, b) {
                        return a.level > b.level ? 1 : a.level < b.level ? -1 : 0;
                    });

                    $(resultHtmlList).empty();
                    $.each(result, function (key, val) {
                        var $li = $("<li><a href='" + val.url + "'>" + val.title + "<small style='color:#999; padding-left:5px;'>" + val.group + "</small>" + "</a></li>");
                        resultHtmlList.append($li);
                    });
                }
                return resultHtmlList;
},
```

**Comment by running-coder** [comment]
hey @Chryogenic indeed if you re-build the complete html you will loose the onClick actions that are binded in Typeahead. By default the sorting is made from the `display:` keys but those keys are also searchable.
```javascript
display: ["level", "title"], // will sort by level
template: '{{title}}', // will only display the title even if the level was matched
```

Ideally `order` option could receive a key/value pair as well as the current `asc/desc`. I'll keek that in mind for a future release.

If you do not want to search in the `level` key you will need to re-order the `<li>`s instead of redoing them which is also doable perhaps inspired by http://jsfiddle.net/f85Ym/.
