### ISSUE TITLE
Cannot get correct matched key when an array is used inside "display" for multiple keys search

### ISSUE THREAD

**Issue by costi31** [running-coder/jquery-typeahead#395]
Greetings,
if I use an array inside "display" property, in order to search through multiple keys, I cannot get the correct matched key.
Example:

```javascript
var data = [
  {
  "id": 105,
  "original_language": "en",
  "original_title": "Back to the Future",
  "alternative_titles": [
    "Tilbage Til Fremtiden",
    "Ritorno al futuro parte I"
    ]

  }]

$('#searchlangs').typeahead({
  minLength: 1,
  maxItem: 8,
  maxItemPerGroup: 6,
  order: "asc",
  hint: true,
  searchOnFocus: true,
  correlativeTemplate: true,
  templateValue: "{{title}}",
  template: "{{title}}",
  matcher: function (item, displayKey) {
    // return modified item object
    item.title = displayKey;
    console.log(item);
    return item;
  },
  display: ["original_title", "alternative_titles"], // allows the Typeahead to search inside these 2 object keys for any results
  emptyTemplate: '<i>No results found for "{{query}}"</i>',        
  source: {
    teams: {
        data: data
    }
  },
  callback: {
    onSubmit: function (node, form, items, event) {
        event.preventDefault();

        alert(JSON.stringify(items))
    }
  },
  debug: true
});
```

Result is this:
![cattura](https://user-images.githubusercontent.com/15123093/32773078-481b68b8-c928-11e7-9357-57df1d49d017.PNG)

and an array is printed as title in the console, instead of a single string.
Normally it should show only "Ritorno al futuro parte I".

**Comment by tombertrand** [comment]
hey @costi31, I was able to repro your issue and I get why you would like to do it this way. Unfortunatly Typeahead was not built to loop inside loop. Currently Typeahead flattens the searched value https://github.com/running-coder/jquery-typeahead/blob/2.10.4/src/jquery.typeahead.js#L1924, so 
```
[
  "Tilbage Til Fremtiden",
  "Ritorno al futuro parte I"
]
```
becomes
`"Tilbage Til Fremtiden, Ritorno al futuro parte I"`

For now, you can loop your displayKey inside the matcher function to match a result and only add that one inside title instead of the full array. 

Typeahead would require an update to support this kind of alternative_titles > array search

**Comment by costi31** [comment]
Thank you for the fast reply!
The reason is a bit hard to explain and long.
In few words: I don't know a priori how many alternative titles there are (different number for different movies), so I decided to use the array.

The long story is that I would like to implement a fast typeahead searchbox that allows to search movies by original title or localized title in desired language, only by using local information stored. The problem is that the TMDb api (where I take movie informations) gives the downloadable dump of movie titles only, but I can retrieve alternative titles and store them with a single request per movie. They don't give me all the official titles for each country of a movie (with a single request), but only alternative titles.

I tried 2 workarounds:

1) change your code inside "searchResultData" function, at beginning of displayKeys loop, to distinguish arrays between keys and add them at runtime to item as new elements.
I did it in this way from line 1882:
```javascript
                    displayKeys = this.options.source[group].display || this.options.display;              
                  
                    for (var v = 0, vv = displayKeys.length; v < vv; ++v) {
                        if (Array.isArray(item[displayKeys[v]]) ) {
                            // In case the key is an array then 
                            for (var z = 0; z < item[displayKeys[v]].length; z++) {
                                item[displayKeys[v] + z] = item[displayKeys[v]][z];
                                displayKeys.push(displayKeys[v] + i);
                                ++ v;
                            }
                            continue;
                        }   
```
 (I know I implemented in a horrible and higly unsafe way, it was only a quick test because I didn't want to change your code too much).

2) create a priori separate keys for each alternative title (alternative_title_0, alternative_title_1,...) of each movie and set all these keys in the display option (up to a fixed number, even if they do not exist for all movies).


Instead, in the solution you proposed, I don't know how to loop my displayKey array inside the matcher function to match the query, because the matcher function arguments are only item and displayKey, not query. Do I have to retrieve it by looking at the html element value or I can find it in another way?

**Comment by tombertrand** [comment]
oh perhaps I've not made it clear in the doc but every Typeahead function are scoped to it's Typeahead instance meaning that if you `console.log(this)` inside the matcher function you should get you Typeahead instance so `this.query` would give you what you are looking for if you want to try "temporary" solution. Indeed I think searching a key that contains an array can be valuable to implement in the long run but I don't have time to look at it soonish. Feel free to implement your solution whenever its editing typeahead.js or splitting the title into _0, _1 suffixed keys. 

Just a note, if you are using `correlativeTemplate` option my solution won't work because it's attempting to match different part of the query and this logic is inside Typeahead.
