### ISSUE TITLE
multiple async ajax sources

### ISSUE THREAD

**Issue by mattiaverga** [running-coder/jquery-typeahead#447]
Hello, I have the following sources:
```
source: {
            packages: {
                ajax: {
                    url: 'packages/?search={{query}}',
                    path: "packages"
                },
            },
            updates: {
                ajax: {
                    url: 'updates/?search={{query}}',
                    path: "updates"
                },
                display: 'title',
            },
            users: {
                ajax: {
                    url: 'users/?search={{query}}',
                    path: "users"
                },
            },
            overrides: {
                ajax: {
                    url: 'overrides/?search={{query}}',
                    path: "overrides"
                },
                display: 'nvr',
            }
},
```
I would like to load the sources in async mode, in the documentation I've found I should use jQuery.Deferred function, but I don't know how to pair it with the `path` option and how to pass the `{{query}}`.

**Comment by bearsworth** [comment]
Hi, I don't quite understand deferred, but wondering if you could help me on using the ajax part since you seem to have it working. Whenever a user hits my url they get this data:

[
{
_id: "5bb09382e9d71b19a3afaedb",
Id: "3808",
Url: "/coins/ltc/overview",
ImageUrl: "/media/19782/litecoin-logo.png",
Name: "LTC",
Symbol: "LTC",
CoinName: "Litecoin",
FullName: "Litecoin (LTC)",
Algorithm: "Scrypt",
ProofType: "PoW",
FullyPremined: "0",
TotalCoinSupply: "84000000",
BuiltOn: "N/A",
SmartContractAddress: "N/A",
PreMinedValue: "N/A",
TotalCoinsFreeFloat: "N/A",
SortOrder: "3",
Sponsored: false,
IsTrading: true
}
]

what would I put for my path: or data: if I wanted just the "CoinName" to appear?

**Comment by bearsworth** [comment]
Nevermind... I got it to work lol.... I have no idea sometimes, if I get the deferred part working I'll get back.

**Comment by running-coder** [comment]
hey @mattiaverga, the `path` option is used for telling Typeahead to look into a specific key for data array from your response. It is an optional configuration, lets say your response comes back as

```
[{
id: 1,
data: 'abc'
}, {
id: 2,
data: 'def'
}]
```

then you wouldn't need `path`. But if your data comes inside a data key then you want to either use the `done` callback to manually format your data or the `path`. To pass the query you can use `this.query` inside any callback function and add it to your url.  Every callback is proxied to its Typeahead instance meaning that all of its properties are accessible via the `this` object. Try it using `console.log(this)` from inside any of the Typeahead callback functions.
