### ISSUE TITLE
Open query search for no match in result set

### ISSUE THREAD

**Issue by connectwithraj** [running-coder/jquery-typeahead#481]
How do we implement open search keyword search when no match is present in result set.
If nothing matches, we want to allow “enter key” and use the query to perform an alternate custom API call.

**Comment by running-coder** [comment]
hi @connectwithraj, following with #427 , have you looked into the `onSubmit` callback?

```javascript
typeof $.typeahead === 'function' && $.typeahead({
    input: ".js-typeahead",
    minLength: 1,
    source: ...,
    callback: {
        onResult: function (node, query, obj, objCount) {
            // As keys are being typed
            console.log(objCount)
        },
        onSubmit: function(node, form, item, event) {
            // prevent the form from submitting
            event.preventDefault();

           // Gives you the current Typeahead object
           // console.log(this);

           // Do Ajax CB here to get extra results if the result set is empty
           if (!this.resultCount) {
             // Do something when there are no results
           } else if (this.resultCount === 1) {
             // Do something when there is 1 result
             console.log(this.result)
           } else {
             // if there are more than 1...
           }
        }
    }
});
```

**Comment by connectwithraj** [comment]
Thanks for your response. I will soon reply back of this works. 

Could you also guide with best practices around how to close/stop result call and re-intialize it? 

When a user starts typing and hits enter key, we want to stop ajax call for results and prevent result container from opening..

But when user starts typing again for next query, we want to re-initialize typeahead to serve next query with result container if required. 

Thanks for your help in advance!

**Comment by tombertrand** [comment]
to cancel "in flight" request you can potentially use the same logic as Typeahead -> https://github.com/running-coder/jquery-typeahead/blob/master/src/jquery.typeahead.js#L849

you should be able to reach the xhr request(s) with `window.Typeahead['YOUR_INPUT_SELECTOR'].xhr`

and use the `onNavigateBefore` callback https://github.com/running-coder/jquery-typeahead/blob/master/src/jquery.typeahead.js#L1550 to listen for an enter keypress (e.keyCode === 13) preventDefault and call `window.Typeahead['YOUR_INPUT_SELECTOR'].hideLayout`

**Comment by vmanickamus** [comment]
Hi,
The onSubmit event is not firing when we type a string and hit enter (unless there is a result  set pre-populated by a search). If there is no matching results set based on a search query, and the user press enter key, we want to do custom search. Since the onSubmit event is not firing, we are not able to do our custom search.
Also when we use hideLayout, the entire search behavior is suppressed along with the hiding of the result container. When a new search is typed the result container is not displayed. What is the better event we can use to rest by showLayout?

**Comment by connectwithraj** [comment]
@tombertrand 
Me and @vmanickamus  are working together on the same problem.

Which CB we should override for window.Typeahead['YOUR_INPUT_SELECTOR'].xhr ?

**Comment by tombertrand** [comment]
could be something like this

https://codesandbox.io/s/jquery-typeahead-c9e0f

**Comment by connectwithraj** [comment]
Can you address this other thread please

https://github.com/running-coder/jquery-typeahead/issues/479

**Comment by connectwithraj** [comment]
@tombertrand  https://codesandbox.io/s/jquery-typeahead-c9e0f
thanks for this! This actually really helped. 

**This code took care of cancelling the request with XHR and closing the result container, if container is visible.** 
BUT
as we start typing (min char =2), and hit enter (type more than 3 letters and then hit enter), result container will still show up. 

How can we solve this?

**Comment by tombertrand** [comment]
it sounds like you want to achieve a very specific behaviour, in that case perhaps instead of `this.hideLayout()` you could add a "hidden" class (display: none;) of your choosing so that way you have control over when you want to display or hide the results

**Comment by connectwithraj** [comment]
Is it possible to have a skype call or some sort of screen sharing where we could show you? 

It will be really helpful!

**Comment by connectwithraj** [comment]
Ping me your email id at connectwithraj@gmail.com, if you can. I will send you screen recording for you to see the behavior.

**Comment by connectwithraj** [comment]
On a different note, what is the best practice for ignoring special characters from being passed into the query? 
how do I pass A, B$ C# D& as "A B C D"?

Should we use accent: {from:"-/'",to:"   "} ?
here I am trying to ignore hyphen, backslash and inverted comma with 3 spaces?

Any documentation?

**Comment by renesansi** [comment]
Hi, thank you for amazing script. I mostly use php, I have really very few knowledge of ajax with javascript. 
I used this code @tombertrand https://codesandbox.io/s/jquery-typeahead-c9e0f
Just kindly ask you to help fixe one issue : 
when user click on enter key => nothing happens, which is good for my case, because I want to force user select result from suggested list of results => presented as links. 
But after when enter key clicked on, script does not react any more. 
I mean if user clicked on accidentally enter key he cannot get new suggested list. 
Please look and check this behaviour here :  https://codesandbox.io/s/jquery-typeahead-c9e0f          
How I can correct this issue. Thank you.

**Comment by tombertrand** [comment]
That example will never submit because there is a `e.preventDefault` in the `onSubmit` callback. If you want to force selecting an item before submitting, you can look into `mustSelectItem` option

http://www.runningcoder.org/jquerytypeahead/documentation/#options-mustSelectItem

new suggestion list not coming back might be a 🐛

**Comment by renesansi** [comment]
> you can look into `mustSelectItem` option
MERCI ! It works!
