### ISSUE TITLE
Do nothing when "enter" pressed?

### ISSUE THREAD

**Issue by cjx2240** [running-coder/jquery-typeahead#506]
Is there a simple means to do absolutely nothing when enter/return is pressed?

Preventing default on the form, or using the onsubmit callback, means it doesn't submit, but it also hides the typeahead results.

Sorry if this has been asked before, hope you can appreciate that it's hard to effectively search the docs for phrases like return key enter etc!

**Comment by tombertrand** [comment]
hey @cjx2240 it's not possible with the existing code because certain behaviors are expected when using that kind of input/search, although you could bind a [keydown](https://github.com/running-coder/jquery-typeahead/blob/master/src/jquery.typeahead.js#L701) event to your input before initializing typeahead that prevents any action when said key is pressed
