### ISSUE TITLE
Is it possible to request the selected item?

### ISSUE THREAD

**Issue by sdillinger** [running-coder/jquery-typeahead#55]
My source data uses a text field as the display, but also provides an object_id (not displayed) that I use server side.

I can get the object_id via the item arg in various callbacks.   Is there a way to access this field directly- by that I mean not as the result of a callback?   

I have other (non-typeahead) events that need access to the 'result' in the typeahead container (the object_id in this case).

**Comment by running-coder** [comment]
Excellent question and this one definitly needs more doc. It is possible for you to access your Typeahead properties using:

```javascript
Typeahead['yourSelector'] // on the window scope
```

You should see the "item" properties that represent your selected item and from there grab the id.
there is an example inside the game_v2 demo at the end of the javascript file.

You may proceed with caution changing these values because it will affect the typeahead internal behaviors but there is no problem for reading.

**Comment by sdillinger** [comment]
Excellent.  Exactly what I was looking for.  Thanks.
