### ISSUE TITLE
Custom search functionality

### ISSUE THREAD

**Issue by neolution-ch** [running-coder/jquery-typeahead#71]
Let's say we have a typeahead for people. In the result we show each person with its name in the format "{FirstName} {LastName}". If I'd search for "Jane Miller" everything would work fine. But if I'd search for "Miller Jane" or "Miller, Jane" it won't.

Is it possible to customize the search functionality of the plugin in that way? And if yes, how?

**Comment by running-coder** [comment]
hey neo,

it is currently not possible, this feature has been requested since a long time by #30 &  #68, perhaps I'll have time to get on it soon..

Thx

**Comment by sdillinger** [comment]
neo-

This is a bit of a hack - but if the alternate searches are limited and know in advance what they are (which is mostly your case) you could add them to the 'display' list so that they are searched.  Then in the template you exclude the alternate values.

Like this:
...
display: ['first_last', 'last_first', 'first_initial_last']
template: '<span>{{first_last}}</span>

values:
'first_last', 'last_first', 'first_initial_last'
Jane Miller, Miller Jane, J Miller

hope this helps.

**Comment by running-coder** [comment]
should now work with the correlativeTemplate option

**Comment by neolution-ch** [comment]
We'll look into it. Thank you very much! :+1:
